"""add_honeytokens

Revision ID: 22fc2cf25186
Revises: add_model_metrics
Create Date: 2025-12-13 01:02:47.333736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '22fc2cf25186'
down_revision: Union[str, Sequence[str], None] = 'add_model_metrics'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('honeytokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('trigger_count', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_honeytokens_token'), 'honeytokens', ['token'], unique=True)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'analyst'::character varying"))
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'analyst'::character varying"))
    op.alter_column('users', 'two_factor_secret',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'is_two_factor_enabled',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.create_index(op.f('ix_model_metrics_timestamp'), 'model_metrics', ['timestamp'], unique=False)
    op.alter_column('model_metrics', 'version',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('model_metrics', 'model_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('model_metrics', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_index(op.f('logs_timestamp_idx'), 'logs', [sa.literal_column('timestamp DESC')], unique=False)
    op.create_index(op.f('idx_logs_timestamp'), 'logs', [sa.literal_column('timestamp DESC')], unique=False)
    op.create_index(op.f('idx_logs_is_reviewed'), 'logs', ['is_reviewed'], unique=False, postgresql_where='(is_reviewed = 0)')
    op.create_index(op.f('idx_logs_final_label'), 'logs', ['final_label'], unique=False, postgresql_where='(final_label = 1)')
    op.alter_column('logs', 'threat_intel',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('logs', 'explanation',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('logs', 'verdict',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('logs', 'sequence_risk',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('logs', 'risk_score',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('logs', 'is_reviewed',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('logs', 'final_label',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('logs', 'predicted_label',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('logs', 'content',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('logs', 'source',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.drop_index(op.f('ix_cluster_cluster_id'), table_name='cluster')
    op.alter_column('cluster', 'confidence',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('cluster', 'is_noise',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('cluster', 'last_seen',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('cluster', 'first_seen',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('cluster', 'representative_log',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('cluster', 'log_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cluster', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'pending'::text"))
    op.alter_column('cluster', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('cluster', 'cluster_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.drop_column('cluster', 'id')
    op.create_index(op.f('ix_audit_logs_username'), 'audit_logs', ['username'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.alter_column('audit_logs', 'details',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'result',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('audit_logs', 'ip_address',
               existing_type=sa.VARCHAR(length=45),
               nullable=False)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('audit_logs', 'username',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('audit_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.add_column('alerts', sa.Column('playbook_action', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('alerts', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('alerts', sa.Column('playbook_timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('alerts_id_timestamp_fkey'), 'alerts', '_hyper_1_15_chunk', ['log_id', 'log_timestamp'], ['id', 'timestamp'], referent_schema='_timescaledb_internal')
    op.create_foreign_key(op.f('alerts_id_timestamp_fkey1'), 'alerts', '_hyper_1_16_chunk', ['log_id', 'log_timestamp'], ['id', 'timestamp'], referent_schema='_timescaledb_internal')
    op.alter_column('alerts', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'New'::text"))
    op.alter_column('alerts', 'rule_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('alerts', 'timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('alerts', 'log_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_table('logcluster',
    sa.Column('log_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cluster_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('log_timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['log_id', 'log_timestamp'], ['_timescaledb_internal._hyper_1_15_chunk.id', '_timescaledb_internal._hyper_1_15_chunk.timestamp'], name=op.f('logcluster_id_timestamp_fkey')),
    sa.ForeignKeyConstraint(['log_id', 'log_timestamp'], ['_timescaledb_internal._hyper_1_16_chunk.id', '_timescaledb_internal._hyper_1_16_chunk.timestamp'], name=op.f('logcluster_id_timestamp_fkey1')),
    sa.ForeignKeyConstraint(['log_id', 'log_timestamp'], ['logs.id', 'logs.timestamp'], name=op.f('logcluster_log_fkey')),
    sa.PrimaryKeyConstraint('log_id', name=op.f('logcluster_pkey'))
    )
    op.drop_index(op.f('ix_logCluster_cluster_id'), table_name='logCluster')
    op.drop_table('logCluster')
    op.drop_index(op.f('ix_honeytokens_token'), table_name='honeytokens')
    op.drop_table('honeytokens')
    # ### end Alembic commands ###
